// phiên bản proto3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: protobuf/hello.proto

// tên package được sinh ra

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message là một đơn vị dữ liệu trong Protobuf
type String struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// chuỗi string được truyền vào hàm RPC
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *String) Reset() {
	*x = String{}
	mi := &file_protobuf_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_protobuf_hello_proto_rawDescGZIP(), []int{0}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_protobuf_hello_proto protoreflect.FileDescriptor

const file_protobuf_hello_proto_rawDesc = "" +
	"\n" +
	"\x14protobuf/hello.proto\x12\x05hello\"\x1e\n" +
	"\x06String\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value25\n" +
	"\fHelloService\x12%\n" +
	"\x05Hello\x12\r.hello.String\x1a\r.hello.StringB\x10Z\x0eprotobuf/hellob\x06proto3"

var (
	file_protobuf_hello_proto_rawDescOnce sync.Once
	file_protobuf_hello_proto_rawDescData []byte
)

func file_protobuf_hello_proto_rawDescGZIP() []byte {
	file_protobuf_hello_proto_rawDescOnce.Do(func() {
		file_protobuf_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_hello_proto_rawDesc), len(file_protobuf_hello_proto_rawDesc)))
	})
	return file_protobuf_hello_proto_rawDescData
}

var file_protobuf_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_hello_proto_goTypes = []any{
	(*String)(nil), // 0: hello.String
}
var file_protobuf_hello_proto_depIdxs = []int32{
	0, // 0: hello.HelloService.Hello:input_type -> hello.String
	0, // 1: hello.HelloService.Hello:output_type -> hello.String
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_hello_proto_init() }
func file_protobuf_hello_proto_init() {
	if File_protobuf_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_hello_proto_rawDesc), len(file_protobuf_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_hello_proto_goTypes,
		DependencyIndexes: file_protobuf_hello_proto_depIdxs,
		MessageInfos:      file_protobuf_hello_proto_msgTypes,
	}.Build()
	File_protobuf_hello_proto = out.File
	file_protobuf_hello_proto_goTypes = nil
	file_protobuf_hello_proto_depIdxs = nil
}
